#!/usr/bin/env python3
"""Tier 3 weekly compaction report — clusters near-duplicate memories by
embedding cosine similarity and proposes merges.

    python scripts/mnemo_compact_report.py
    python scripts/mnemo_compact_report.py --project hermes
    python scripts/mnemo_compact_report.py --threshold 0.92 --output ./duplicate-report.md
    python scripts/mnemo_compact_report.py --discord-webhook https://discord.com/api/webhooks/...

Without --output/-discord-webhook, the report prints to stdout as Markdown.
With --discord-webhook, it POSTs the report body to the Discord channel
(used by the cron job in scripts/cron-mnemo-compact.sh if you wire one up).
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import urllib.request
import urllib.error

from mnemo_common import auth_headers, build_url, get_base_url, load_env, request_with_retry


def _parse_embedding(raw) -> list[float]:
    if not raw:
        return []
    try:
        parsed = json.loads(raw)
        if isinstance(parsed, list) and all(isinstance(x, (int, float)) for x in parsed):
            return [float(x) for x in parsed]
    except (TypeError, ValueError):
        pass
    return []


def _cosine(a: list[float], b: list[float]) -> float:
    if not a or not b or len(a) != len(b):
        return 0.0
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(x * x for x in b))
    if na == 0 or nb == 0:
        return 0.0
    return dot / (na * nb)


def fetch_all(env: dict, project: str) -> list[dict]:
    """GET /api/memories as JSON for the given project (or 'all')."""
    base = get_base_url(env)
    headers = auth_headers(env)
    url = build_url(base, "/api/memories", {"project": project, "limit": 200})
    out: list[dict] = []
    offset = 0
    while True:
        params = {"project": project, "limit": 200, "offset": offset}
        u = build_url(base, "/api/memories", params)
        resp = request_with_retry("GET", u, headers=headers)
        if resp.status_code != 200:
            sys.stderr.write(f"HTTP {resp.status_code} at offset {offset}\n")
            break
        rows = resp.json()
        if not rows:
            break
        out.extend(rows)
        if len(rows) < 200:
            break
        offset += 200
    return out


def cluster_duplicates(items: list[dict], threshold: float) -> list[list[dict]]:
    """Greedy clustering by embedding cosine similarity.

    Returns clusters of size >= 2 (skip singletons; they're not duplicates).
    Uses pairwise iteration — O(n^2) but fine for the few-hundred-memories
    case the report runs weekly against.
    """
    embedded: list[tuple[dict, list[float]]] = []
    for m in items:
        emb = _parse_embedding(m.get("embedding"))
        if emb:
            embedded.append((m, emb))

    clusters: list[list[dict]] = []
    seen: set[str] = set()

    for i, (ma, ea) in enumerate(embedded):
        if ma["id"] in seen:
            continue
        current: list[dict] = [ma]
        seen.add(ma["id"])
        for j in range(i + 1, len(embedded)):
            mb, eb = embedded[j]
            if mb["id"] in seen:
                continue
            sim = _cosine(ea, eb)
            if sim >= threshold:
                current.append(mb)
                seen.add(mb["id"])
        if len(current) >= 2:
            clusters.append(current)
    return clusters


def render_report(env: dict, project: str, threshold: float, clusters: list[list[dict]]) -> str:
    base = get_base_url(env)
    lines: list[str] = []
    lines.append(f"# Mnemo duplicate report — project=`{project}` threshold={threshold}")
    lines.append("")
    lines.append(f"_Generated by `mnemo_compact_report.py` — see `README.md`._")
    lines.append("")
    lines.append(f"Found **{len(clusters)}** candidate cluster(s):")
    lines.append("")
    for idx, cluster in enumerate(clusters, 1):
        lines.append(f"## Cluster {idx} ({len(cluster)} memories)")
        lines.append("")
        for m in cluster:
            tags = " ".join(f"#{t}" for t in (m.get("tags") or []))
            lines.append(
                f"- **{m['title']}** (updated {m['updatedAt'][:10]}, imp {m['importance']}) — {m['content'][:200]}{'…' if len(m['content']) > 200 else ''} {tags}"
            )
            lines.append(f"  - id: `{m['id']}`  ·  [view]({base}/memories/{m['id']})")
        lines.append("")
        # Suggest keep newest, delete the rest.
        keep = sorted(cluster, key=lambda x: x["updatedAt"], reverse=True)[0]
        lines.append(
            f"**Suggested action:** keep `{keep['id']}` ({keep['title']}) and soft-delete the others."
        )
        lines.append("")
    return "\n".join(lines)


def post_to_discord(webhook: str, content: str) -> bool:
    """POST a message to a Discord webhook. Expects webhook URL with /messages or /execute."""
    url = webhook
    try:
        parsed = urlparse(url)
        if parsed.scheme not in ("http", "https"):
            sys.stderr.write(f"webhook URL must be http(s): {url}\n")
            return False
    except Exception as e:
        sys.stderr.write(f"bad webhook URL: {e}\n")
        return False
    data = json.dumps({"content": content[:1990]}).encode("utf-8")  # discord limit
    req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            ok = 200 <= resp.status < 300
            sys.stderr.write(f"# discord webhook {resp.status}\n")
            return ok
    except urllib.error.HTTPError as e:
        sys.stderr.write(f"# discord webhook HTTP {e.code}\n")
        return False
    except urllib.error.URLError as e:
        sys.stderr.write(f"# discord webhook error: {e}\n")
        return False


def main() -> int:
    p = argparse.ArgumentParser(description="Mnemo weekly duplicate-compaction report")
    p.add_argument("--project", default="all")
    p.add_argument("--threshold", type=float, default=0.88,
                   help="cosine similarity threshold (default 0.88)")
    p.add_argument("--output", "-o", default=None,
                   help="write report to this file (default: stdout)")
    p.add_argument("--json", dest="as_json", action="store_true",
                   help="emit JSON instead of Markdown")
    p.add_argument("--discord-webhook", dest="discord_webhook", default=None,
                   help="POST the report to a Discord webhook (in addition to file/stdout)")
    args = p.parse_args()

    env = load_env()
    items = fetch_all(env, args.project)
    if not items:
        sys.stderr.write(f"no memories for project={args.project}\n")
        return 1

    clusters = cluster_duplicates(items, args.threshold)

    if args.as_json:
        body = json.dumps(
            {
                "project": args.project,
                "threshold": args.threshold,
                "memory_count": len(items),
                "cluster_count": len(clusters),
                "clusters": clusters,
            },
            indent=2,
        )
    else:
        body = render_report(env, args.project, args.threshold, clusters)

    if args.output:
        out = Path(args.output).expanduser().resolve()
        out.write_text(body, encoding="utf-8")
        sys.stderr.write(f"# wrote {out} (clusters={len(clusters)})\n")
    else:
        sys.stdout.write(body)
        if not body.endswith("\n"):
            sys.stdout.write("\n")

    if args.discord_webhook:
        ok = post_to_discord(args.discord_webhook, body)
        if not ok:
            sys.stderr.write("discord webhook post failed (continuing)\n")
            return 2

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
